// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list_novedades.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function anonClient() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_novedades_default = defineTool({
  name: "list_novedades",
  title: "Listar novedades publicadas",
  description: "Devuelve las \xFAltimas novedades publicadas de la Maestr\xEDa en Circulaci\xF3n Pulmonar.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("M\xE1ximo de novedades a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const { data, error } = await anonClient().from("novedades").select("id, title, slug, excerpt, published_at").eq("status", "published").order("published_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_ateneos.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function anonClient2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_ateneos_default = defineTool2({
  name: "list_ateneos",
  title: "Listar ateneos",
  description: "Devuelve los ateneos acad\xE9micos disponibles.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("M\xE1ximo de ateneos a devolver.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const { data, error } = await anonClient2().from("ateneos").select("id, titulo, descripcion, fecha, categoria").order("fecha", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_my_profile.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function userClient(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Obtener mi perfil",
  description: "Devuelve el perfil del usuario autenticado en el Campus de la Maestr\xEDa.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await userClient(ctx).from("profiles").select("id, user_id, full_name, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/create_forum_post.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function userClient2(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_forum_post_default = defineTool4({
  name: "create_forum_post",
  title: "Crear publicaci\xF3n en el foro",
  description: "Crea una nueva publicaci\xF3n en el foro acad\xE9mico como el usuario autenticado.",
  inputSchema: {
    title: z3.string().trim().min(3).max(200).describe("T\xEDtulo de la publicaci\xF3n."),
    content: z3.string().trim().min(10).describe("Contenido de la publicaci\xF3n."),
    category: z3.string().trim().min(1).describe("Categor\xEDa del foro (por ejemplo: general, casos, investigacion)."),
    excerpt: z3.string().trim().max(300).optional().describe("Resumen breve opcional.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, category, excerpt }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const { data, error } = await userClient2(ctx).from("forum_posts").insert({
      user_id: ctx.getUserId(),
      title,
      content,
      category,
      excerpt: excerpt ?? null,
      status: "published"
    }).select("id, title, category, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Publicaci\xF3n creada: ${data.id}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tvgkinrbtnbtseooaiex";
var mcp_default = defineMcp({
  name: "maestria-cp-mcp",
  title: "Maestr\xEDa CP \u2013 Agent Tools",
  version: "0.1.0",
  instructions: "Herramientas de la Maestr\xEDa en Circulaci\xF3n Pulmonar. Usa list_novedades y list_ateneos para consultar contenido p\xFAblico. Con el usuario autenticado, get_my_profile devuelve su perfil y create_forum_post publica en el foro.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_novedades_default, list_ateneos_default, get_my_profile_default, create_forum_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
